version: '3'
services:
  app:
    build: .
    ports:
      - '3500:3500' # Expose the HTTP port
    environment:
      - ENV_MONGO=mongodb://db:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.2.9
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - '27017:27017' # Expose the MongoDB port