apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app-chart.fullname" . }}
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.containerPort }}
